### ISSUE TITLE
They don't scale

### ISSUE THREAD

**Issue by MaikLutze** [jydesign/Sketch-Hunt_Arrows-and-Lines-Pack#3] opened 2017-02-20 03:14 UTC
Hello,

I'm not sure whether I'm doing something wrong, but none of the arrows scale as intended, have a look at the attached. Is this related to Sketch version?
thanks a million for a tip.
Maik

![screen shot 2017-02-20 at 11 13 02](https://cloud.githubusercontent.com/assets/25891258/23110613/a0a36d66-f75d-11e6-8c70-63ed8599449c.png)

**Comment by jydesign** [comment] 2017-02-20 14:03
Hi @MaikLutze 

Thanks for sharing that. 

1. The left-most example is not a bug per se. That arrow object can be scaled to be wider or slimmer. If you want to scale it proportionally, please use the 'Scale' command to get the desired height, then set it's desired width with proportions toggle off or by hand scaling width L or R.

2. Could you please tell me the name of the symbol that appears to be scaling oddly at right in your example?

**Comment by MaikLutze** [comment] 2017-02-21 09:23
Thanks,

1. The ‘scale’ comment is greyed-out when selecting the symbols on stage, so I can’t use that and using the ‘size’ properties will distort them. Is there another scaling function?

2. I did a check on another computer and realized that the scaling problem for the small arrows is related to sketch/system version – Our work Macs are locked in on Yosemite with a pre-Sketch42 version. On Sierra with Sketch 42, however, scaling works like a charm.

thanks heaps for the quick help!
M

**Comment by jydesign** [comment] 2017-02-21 15:17
1. Ah yes, sorry I always forget Scale is disabled on Symbols. But the sizing limitations are the same. To adjust, toggle the proportional lock on size inputs. Set first to the desired height, then you can un-toggle constraint lock and adjust width either by manually dragging or entering a value.

I'm going to close this issue for now, but let me know if you run into any other issues, thx.

**Closed as completed by jydesign** 2017-02-21 15:17 UTC
